language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet publish WebApi/WebApi.csproj -c Release
 - dotnet /home/travis/build/Lolialoneathome/FatDairy/WebApi/bin/Release/netcoreapp2.0/publish/WebApi.dll